//TODO:
//  for a canvas feel -- can use a large PNG
//  for a grid -- can use

import type {NextPage} from 'next'
import Head from "next/head";
import initializeApollo from "../lib/apollo";
import {gql} from "@apollo/client";
import HomePage from "../components/HomePage";

export async function getStaticProps(context) {
    const client = initializeApollo();
    const {data} = await client.query({
        query: gql`query getRatings {
            ratings {
                id
                reviewer
                comment
                rate
            }
        }`
    })

    return {
        props: {
            ratings: data.ratings
        }
    }
}

const textToLoad: string = "Hey!%20I'm";

const Home: NextPage = ({ratings}) => {
    return (
        <>
            <Head>
                <title>Yug Gajjar</title>
                {/* TODO: meta tags */}
                <meta name="Yug Gajjar Portfolio" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>

                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                <link href={`https://fonts.googleapis.com/css2?family=Dancing+Script&text=${textToLoad}:wght@500&display=swap`} rel="stylesheet" />
            </Head>

            <HomePage ratings={ratings}/>
        </>
    )
}

export default Home
