import type {NextPage} from 'next'
import Head from "next/head";
import initializeApollo from "../lib/apollo";
import {gql, useQuery} from "@apollo/client";
import {useEffect} from "react";

export async function getStaticProps(context) {
    // const options = {
    //     method: 'POST',
    //     headers: {
    //         'x-hasura-admin-secret': 'boC5iHfKZM564RvZZ5UPpL9lp3MZLi2hMtKGsiU61P1sFRIjdzRbiRHIt6jDv3ap'
    //     },
    //     body: JSON.stringify({
    //         query: `query getRatings {
    //             ratings {
    //                 id
    //                 reviewer
    //                 comment
    //                 rate
    //             }
    //         }`,
    //         operationName: "getRatings"
    //     })
    // }
    //
    // const fetchResponse = await fetch('https://amusing-krill-94.hasura.app/v1/graphql', options)
    // const responseJson = await fetchResponse.json()

    const client = initializeApollo();
    const {data} = await client.query({
        query: gql`query getRatings {
            ratings {
                id
                reviewer
                comment
                rate
            }
        }`
    })

    return {
        props: {
            ratings: data.ratings
        }
    }
}

const Home: NextPage = ({ratings}) => {
    const FETCH_RATINGS = gql`query getRatings {
        ratings {
            id
            reviewer
            comment
            rate
        }
    }`;

    const{loading, error, data} = useQuery(FETCH_RATINGS)

    useEffect(() => {
        console.log(data)
    }, [data])

    return (
        <>
            <Head>
                <title>Yug Gajjar</title>
                {/* TODO: meta tags */}
                <meta name="Yug Gajjar Portfolio" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                {ratings.map((rating) => (
                    <div>{rating.rate}</div>
                ))}
            </main>
        </>
    )
}

export default Home
