//TODO:
//  for a canvas feel -- can use a large PNG
//  for a grid -- can use

import type {NextPage} from 'next'
import Head from "next/head";
import initializeApollo from "../lib/apollo";
import {gql, useQuery} from "@apollo/client";
import {useEffect, useRef} from "react";
import Typed from "typed.js";
import HomePage from "../components/Common/HomePage";

export async function getStaticProps(context) {
    const client = initializeApollo();
    const { data } = await client.query({
        query: gql`query getRatings {
            ratings {
                id
                reviewer
                comment
                rate
            }
        }`
    })

    return {
        props: {
            ratings: data.ratings
        }
    }
}

const Home: NextPage = ({ratings}) => {
    return (
        <>
            <Head>
                <title>Yug Gajjar</title>
                {/* TODO: meta tags */}
                <meta name="Yug Gajjar Portfolio" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
               <HomePage ratings={ratings}/>
            </main>
        </>
    )
}

export default Home
